### ISSUE TITLE
Example is outdated

### ISSUE THREAD

**Issue by hadisfr** [aurora/flowdesigner#2]
Example is compatible with https://github.com/aurora/flowdesigner/releases/tag/v0.1.0. After that, there were a complete rewrite, but example was not updated. There is no `diagram.defineNode` in the current version of code.

**Comment by aurora** [comment]
Mmmm ... you are right. I think i should be able to provide an updated example, if needed. I would just have to extract it from the actual application i am using this ...

**Comment by hadisfr** [comment]
Yes please. I was thinking to reading the codes and updating the example, but it takes much shorter time from you, I think.

**Comment by aurora** [comment]
I fixed the example. So at least the nodes are now visible and you can manually create wires. Looking at the code, this seems a little unfinished :) ... i think i just stopped when it was working for my own purpose. I think i should clean up the code and polish it. There should be a diagram.render() method for example rather than having to call render for each node. Etc. ...
